### ISSUE TITLE
Use proper configuration templates and mechanisms

### ISSUE THREAD

**Issue by omaciel** [RazTamir/bugzilla-reports-tool#27]
Right now one needs to modify actual `*.py` files to include credentials to GMAIL and BUGZILLA, which is a no-no. Instead, please consider reading this information from a standard configuration file, using well-known formats such as yaml, json, toml, etc. Furthermore, don't store the configuration file in the source code, but instead, require it to be created.

**Comment by RazTamir** [comment]
@omaciel ,

What do you think is the best approach to change this to yaml, for example, after there are already users who use this approach?

**Comment by omaciel** [comment]
@RazTamir you can always try to import the module and check if the variables you're expecting to be filled are non-blank. If they are, then you can resort to reading the information from a configuration file.

**Comment by RazTamir** [comment]
OK,
I have the yml cfg file and will notify the existing users about this change.

Thanks

**Comment by StLuke** [comment]
easy way to do this is to have it overridable with ENV variables, therefore you can add them in ie. jenkins job, without the necessity of changing any files.

**Comment by RazTamir** [comment]
This is already fixed and a yaml file is used for configurations.
